"""2 migration

Revision ID: 672d7b1b9d62
Revises: 9079bd732fac
Create Date: 2023-11-23 00:32:58.429608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672d7b1b9d62'
down_revision: Union[str, None] = '9079bd732fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('approver', sa.Boolean(), nullable=True),
    sa.Column('manager', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_admin'), 'roles', ['admin'], unique=False)
    op.create_index(op.f('ix_roles_approver'), 'roles', ['approver'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_manager'), 'roles', ['manager'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_manager'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_approver'), table_name='roles')
    op.drop_index(op.f('ix_roles_admin'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
